version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    environment:
      COVERALLS_REPO_TOKEN: 9lr5EFkAyIgc2eZ3CC4dQ5agO69lTgXQY
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
workflows:
    build-and-test:
      jobs:
        - build-and-test
